[package]
name = "minigrep_jeck"
version = "0.1.1"
edition = "2021"
description = "`minigrep` is a grep clone that takes a query and searches for the query in the file; with added support for regex."
license = "MIT"

[dependencies]
regex = { version = "1.11.1", features = [] }
